WITH UNAVAILABLE AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= DATE('2022-11-30') AND END_DATE >= DATE('2022-11-01')
)
SELECT c.CAR_ID,
       c.CAR_TYPE,
       FLOOR(c.DAILY_FEE * 30 * ((100 - p.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS p
ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단', 'SUV')
  AND c.CAR_ID NOT IN (SELECT CAR_ID FROM UNAVAILABLE)
  AND FLOOR(c.DAILY_FEE * 30 * ((100 - p.DISCOUNT_RATE) / 100)) >= 500000
  AND FLOOR(c.DAILY_FEE * 30 * ((100 - p.DISCOUNT_RATE) / 100)) <= 2000000
ORDER BY 
  FEE DESC,
  c.CAR_TYPE,
  c.CAR_ID DESC;