SELECT
  YEAR(os.SALES_DATE) AS YEAR,
  MONTH(os.SALES_DATE) AS MONTH,
  COUNT(DISTINCT ui.USER_ID) AS PURCHASED_USERS,
  ROUND(
      COUNT(DISTINCT ui.USER_ID) /
      (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),
      1
  ) AS PUCHASED_RATIO
FROM USER_INFO AS ui
INNER JOIN ONLINE_SALE AS os
  ON ui.USER_ID = os.USER_ID
WHERE YEAR(ui.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;