SELECT 
  fp.PRODUCT_ID,
  fp.PRODUCT_NAME,
  SUM(fp.PRICE * fo.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS fp
JOIN FOOD_ORDER AS fo 
  ON fp.PRODUCT_ID = fo.PRODUCT_ID
WHERE fo.PRODUCE_DATE >= '2022-05-01' 
  AND fo.PRODUCE_DATE <= '2022-05-31'
GROUP BY fp.PRODUCT_ID, fp.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;