SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d')
FROM MEMBER_PROFILE AS m
JOIN REST_REVIEW AS r
  ON m.MEMBER_ID = r.MEMBER_ID
WHERE r.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(cnt)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS cnt
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS T 
    )
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;