SELECT fi.ID, fn.FISH_NAME, fi.LENGTH
FROM FISH_INFO AS fi
JOIN FISH_NAME_INFO AS fn
ON fi.FISH_TYPE = fn.FISH_TYPE
WHERE fi.LENGTH = (
    SELECT MAX(fi2.LENGTH)
    FROM FISH_INFO AS fi2
    WHERE fi.FISH_TYPE = fi2.FISH_TYPE
)
ORDER BY fi.ID ASC;